Add quality control module
NBISweden/LocalEGA pull request #309
Opened 2018-06-19 13:02 UTC by dtitov

Microservice for Quality Control. Sources are available here: https://github.com/NBISweden/LocalEGA-QC

The architecture is plugin-based: all the specific QC's can be added as implementations of the provided interface. Currently, there's one mandatory QC there: checksum validation (ex-`verify` microservice). Afterwards, there will be added one more mandatory QC: mappings creation for HTSGET protocol. 

This implementation uses HTSJDK library for random access to files (https://github.com/samtools/htsjdk) and Java implementation of Crypt4JH (https://github.com/uio-bmi/crypt4gh).

2018-06-19 13:10 UTC, silverdaz requested changes
Does this remove the verify container and therefore the verify ?

2018-06-19 13:12 UTC, dtitov commented
It includes the `verify` functionality, so yes, it assimilates `verify` container.

2018-06-19 13:14 UTC, silverdaz commented on deployments/docker/bootstrap/lega.sh
> +  qc:
Or is it just that the diff view was showing me a weird combination?

2018-06-19 13:17 UTC, silverdaz commented
Then don't. Just ignore the verify container.
Assume that you do the QC reading the message from the QC queue, *after* the verify step.

2018-06-21 10:57 UTC, dtitov commented
@silverdaz, I've added a possibility to use filesystem-based storage.

@blankdots, if you want to look into sources itself, they are there: https://github.com/NBISweden/LocalEGA-QC

2018-06-21 11:26 UTC, silverdaz commented
ok, good job, thanks.

I don't however believe that the verification module should be in another repo.
I think the checksum is a prerequisite, for the submission part, and could be separate from the rest. Those prerequisites could change, of course, but they probably won't change that often.
(and in such a case, we update the module).

I think it should be part of the repo, so that `git clone [that-repo]` contains everything.

2018-06-21 11:28 UTC, silverdaz commented
To me, make your code skip the checksum.
The verify container as it is remains unchanged and then we plug the htsget code in, to see how things behave.

2018-06-21 11:41 UTC, dtitov commented
> I don't however believe that the verification module should be in another repo.
I think the checksum is a prerequisite, for the submission part, and could be separate from the rest. Those prerequisites could change, of course, but they probably won't change that often.
(and in such a case, we update the module).

I've been thinking about that as well. There are pros and cons.

Pros: we will have everything in one place making it easy to just go for `git clone` to get the whole thing at once, as you mentioned.

Cons: The Travis configuration well become more complicated as I will definitely add unit-tests to this module, which means that we will have to support both unit-testing platforms in one repo, for Python and for Java.

Also, note that if we look as an example at EGA DAta Out API, they have all the microservices split into different repos.

2018-06-21 11:41 UTC, dtitov commented
> To me, make your code skip the checksum.
The verify container as it is remains unchanged and then we plug the htsget code in, to see how things behave. 

It'is not what we agreed on during today's Sprint Review, is it? As far as I remember, we agreed that it's nice idea to have modularity (plugin-based mechanism) for **potential** validators, yet having currently only one validation active: checksumming. With this approach the current flow will not be changed - we will just get the possibility to add more validators in the future. One of the upcoming validators will be the indexing one for HTSGET, but I will need time to implement it. And currently the verify container will turn into verify plugin for QC. Or do I misunderstand the conclusions of our today's discussion?

2018-06-21 11:52 UTC, blankdots commented on deployments/docker/bootstrap/lega.sh
>      volumes:
is the LocalEGA-QC really using this, maybe i missed in the code ? 
also from what it seems the QC is using different vars/kind of configuration https://github.com/NBISweden/LocalEGA-QC/blob/master/src/main/resources/application.properties with some match to existing Env vars, still things like `spring.rabbitmq.addresses=amqp://guest:guest@mq:5672` not sure how these will be manageable in order to support all deployments (maybe to a certain extent reuse the same names from https://github.com/NBISweden/LocalEGA/wiki/Configuration-Settings-%7C-Environment-Variables)
Maybe we can find a way so that we don't manage multiple configuration files and formats.
If I would like to provide a different configuration file, I would have to do a different image or can I inject a configMap?

2018-06-21 12:09 UTC, viklund commented
During the review I didn't understand how this plugin mechanism was implemented. I thought this was _only_ a plugin running the checksum validation. Not a complete Java framework for writing plugins with one plugin in it. How plugins are implemented and run needs more work and thinking before this is done since this needs to sync up with more parties (i.e. we want to be able to easily move plugins to and from cEGA).

I also don't think that the plugin framework should mandate an implementation language.

Also I think it should be called "File Processors" instead of "QC"/"Quality Control" (because the htsget thing for example is not QC).

2018-06-21 12:23 UTC, dtitov commented
@viklund, since it's conceptual/architectural comment that potentially can bring up a heavy discussion, I propose to move it to Slack.

2018-06-22 07:12 UTC, dtitov commented on deployments/docker/bootstrap/lega.sh
>      volumes:
Yes, it uses it to connect to DB. Almost all the Items in `application.properties` are built based on env-vars provided to the container. So you don't have to put any extra files to this container to configure it - just set and pass corresponding env vars, that's it.

2018-06-25 04:46 UTC, blankdots commented on deployments/docker/bootstrap/lega.sh
>      volumes:
I was referring to line with `volumes` I did not find its contents anywhere used in the LocalEGA-QC used (meaning `- ./lega/conf.ini:/etc/ega/conf.ini:ro`) 
> Almost all the Items 

well as it is right now for Kubernetes there is a need for the message broker username, password, address and port to be configurable :) ... is it possible to make them all configurable ? and/or have the option to inject a new `application.properties`

2018-06-25 09:00 UTC, dtitov commented on deployments/docker/bootstrap/lega.sh
>      volumes:
Ah, I see. Well, it's not used at the moment, but I kept its injection in the compose-file just in case. And yes, I'll make broker credentials be configurable.

2018-06-28 09:45 UTC, closed without merging