Feature/encrypt keys ini
NBISweden/LocalEGA pull request #324
Opened 2018-07-23 09:45 UTC by silverdaz

`keys.ini` is:
* encrypted,
* not in cleartext on disk.

The keyserver loads the file and decrypts it (using `LEGA_PASSWORD`).
Decryption calls `openssl` as it is quicker than coding the AES decryption. Maybe simpler too.

2018-07-23 09:57 UTC, blankdots commented on deployments/docker/test/Makefile
> +MAIN_REPO=~/_ega
It was like that `~/_ega` but, I would still keep `~/LocalEGA` to make it clear for everyone that is the LocalEGA repo and everyone that uses this test script changes accordingly to their path; I also am changing every time on my machine. 
Not a big deal, nitpicking :)

2018-07-23 10:09 UTC, silverdaz commented on deployments/docker/test/Makefile
> +MAIN_REPO=~/_ega
Yeah. My bad. Let's keep it as `~/LocalEGA`.

2018-07-24 05:40 UTC, blankdots requested changes
I think we should have Keyserver configuration decrypted in code

2018-07-24 05:40 UTC, blankdots commented on lega/conf/__init__.py
> +            s = "openssl enc -aes-256-cbc -d -in {} -k {}".format(str(filepath), os.environ.get('LEGA_PASSWORD',None))
Use solution provided by: https://github.com/NBISweden/LocalEGA/issues/325

2018-07-24 11:19 UTC, blankdots approved these changes

2018-07-24 11:26 UTC, merged