Docker Swarm deployment
NBISweden/LocalEGA pull request #326
Opened 2018-07-23 13:38 UTC by dtitov

Here we go. I'm going to record a video for the whole process tomorrow, but there are already instructions available in `README.md`, so the review can be started.

2018-07-24 05:43 UTC, blankdots commented on deployments/swarm/.gitignore
> +.idea
the `.gitignore` for Gradle and Intellij should be a bit more complex .. in case of doubt use e.g. https://www.gitignore.io/api/gradle,intellij+all

2018-07-24 07:57 UTC, blankdots requested changes
Some changes please:
* There is limited support for docker swarm in https://github.com/gesellix/gradle-docker-plugin/blob/master/supported-api.md see if it can be used instead of exec tasks
* Please consider converting some of the tasks to https://docs.gradle.org/current/userguide/custom_tasks.html we can discuss which ones
* Use https://github.com/chrisgahlert/gradle-dcompose-plugin

My understanding is that this deployment assumes that a cluster is existing not created.

2018-07-24 07:57 UTC, blankdots commented on deployments/swarm/cega/build.gradle
> +            args "stack", "deploy", "--compose-file", "docker-stack.yml", "cega"
Instead of using a predefined `docker-stack.yml` file you can generate one with https://github.com/chrisgahlert/gradle-dcompose-plugin along with the necessary custom configuration

2018-07-24 07:57 UTC, blankdots commented on deployments/swarm/lega/build.gradle
> +            args "stack", "deploy", "--compose-file", "docker-stack.yml", "lega"
the same as in the cega case, there are plugins to make it easier

2018-07-24 08:00 UTC, silverdaz commented on deployments/docker/images/mq/entrypoint.sh
> +# chmod 640 /etc/rabbitmq/defs.json
The rabbitmq user and group don't need to own the files anymore?
I guess it's root then, and you showed it works?

2018-07-24 08:02 UTC, dtitov commented on deployments/docker/images/mq/entrypoint.sh
> +# chmod 640 /etc/rabbitmq/defs.json
There’s a problem with `chown` and `chmod` in Swarm, because configs are injected read-only. So I skipped this step and it still worked, yes.

2018-07-24 08:06 UTC, silverdaz commented on deployments/docker/images/mq/entrypoint.sh
> +# chmod 640 /etc/rabbitmq/defs.json
And what if they are not injected as read-only? Have you tried?

My guess was that the rabbitmq utility was run as the rabbitmq user/group, so I made them own the files, just in case. But maybe I was wrong and it is run as root. I will check.

2018-07-24 08:19 UTC, dtitov commented on deployments/docker/images/mq/entrypoint.sh
> +# chmod 640 /etc/rabbitmq/defs.json
I'm not sure if I understand correctly, but I just can't inject Docker configs not as read-only, as per Docker configs mounting description:
> The permissions for the file that is mounted within the service’s task containers, in octal notation. For instance, `0444` represents world-readable. The default is `0444`. Configs cannot be writable because they are mounted in a temporary filesystem, so if you set the writable bit, it is ignored. The executable bit can be set.

2018-07-24 08:21 UTC, dtitov commented on deployments/swarm/.gitignore
> +.idea
Didn't know about such a nice service, thanks.

2018-07-24 08:30 UTC, dtitov commented on deployments/swarm/cega/build.gradle
> +            args "stack", "deploy", "--compose-file", "docker-stack.yml", "cega"
This was my conscious decision. I'm not in favor of generating Compose files. We used to have them static before in LocalEGA, but then, for some reason, changed to generate them, but I never really liked this idea. So in this deployment, I decided to go away from that.

2018-07-24 08:30 UTC, dtitov commented on deployments/swarm/lega/build.gradle
> +            args "stack", "deploy", "--compose-file", "docker-stack.yml", "lega"
Same as above.

2018-07-24 08:56 UTC, silverdaz commented on deployments/docker/images/mq/entrypoint.sh
> +# chmod 640 /etc/rabbitmq/defs.json
You understand it correctly. Not writable bit: read-only (we don't care about the exec bit).
What do they say about ownership?
Isn't it a bit strange that you can't tell who owns the files?

Side note: I have checked, the rabbitmq-server is run under the rabbitmq user (and /var/lib/rabbitmq is chowned to rabbitmq too). That's why I made the rabbitmq own /etc/rabbitmq too.

2018-07-24 08:58 UTC, dtitov commented on deployments/docker/images/mq/entrypoint.sh
> +# chmod 640 /etc/rabbitmq/defs.json
```
# ls -la /etc/rabbitmq/               
total 24
drwxrwsrwx 1 rabbitmq rabbitmq 4096 Jul 24 08:57 .
drwxr-xr-x 1 root     root     4096 Jul 24 08:57 ..
-rw-r--r-- 1 root     rabbitmq 1173 Jul 24 08:57 defs-cega.json
-r--r--r-- 1 root     root     1813 Jul 24 08:57 defs.json
-rw-r--r-- 1 root     rabbitmq  117 Jul 24 08:57 enabled_plugins
-r--r--r-- 1 root     root      519 Jul 24 08:57 rabbitmq.config
```

2018-07-24 09:06 UTC, silverdaz commented on deployments/docker/images/mq/entrypoint.sh
> +# chmod 640 /etc/rabbitmq/defs.json
and `ls -lad /etc/rabbitmq`?

2018-07-24 09:09 UTC, dtitov commented on deployments/docker/images/mq/entrypoint.sh
> +# chmod 640 /etc/rabbitmq/defs.json
```
# ls -lad /etc/rabbitmq
drwxrwsrwx 1 rabbitmq rabbitmq 4096 Jul 24 09:08 /etc/rabbitmq
```

2018-07-24 09:23 UTC, silverdaz commented on deployments/docker/images/mq/entrypoint.sh
> +# chmod 640 /etc/rabbitmq/defs.json
ok, thanks. I was just curious.

The 's' bit is set, that's why the created files `defs-cega.json` and `enabled_plugins` get rabbitmq as their group. The ingected file get root, and I guess the Swarm mounting driver does allow you to change the ownership.

It's ok, the files are world-readable. So it still works even without the rabbitmq ownership.

2018-07-24 09:55 UTC, silverdaz requested changes
I would prefer to keep the ownership.
Can you try?
```
{
    chown     ...
    chmod     ...
    ....    the rest  ....
} || true
```

2018-07-24 10:45 UTC, dtitov commented
@silverdaz, yes, it worked. Done.

2018-07-24 10:50 UTC, silverdaz requested changes
more places for `... || true`

2018-07-24 10:50 UTC, silverdaz commented on deployments/docker/images/mq/entrypoint.sh
> +# chown -R rabbitmq /var/lib/rabbitmq
You can delete that line, I saw it in the docker-entrypoint.sh of the docker hub rabbitmq image.

2018-07-24 10:50 UTC, silverdaz commented on deployments/docker/images/mq/entrypoint.sh
> +# chown rabbitmq:rabbitmq /etc/rabbitmq/defs-cega.json
```{
    ....
} || true
```
here as well

2018-07-24 10:54 UTC, silverdaz approved these changes
Good to go for me

2018-07-25 05:29 UTC, blankdots commented
For starting a swarm cluster (using virutalbox) one can use (don't consider it the best option):
```bash
#!/usr/bin/env bash

case $1 in
  start)
    begin=$(date +%s)
    for ((i=1;i<=$2;i+=1)); do
      docker-machine create -d virtualbox --virtualbox-memory "4096" lega-swarm-$i
    done

    eval $(docker-machine env lega-swarm-1)

    docker swarm init \
      --advertise-addr $(docker-machine ip lega-swarm-1)

    TOKEN=$(docker swarm join-token -q worker)

    if [ $2 -gt 1 ]
    then
      for ((i=2;i<=$2;i+=1)); do
        eval $(docker-machine env lega-swarm-$i)

        docker swarm join \
          --token $TOKEN \
          --advertise-addr $(docker-machine ip lega-swarm-$i) \
          $(docker-machine ip lega-swarm-1):2377
      done
    fi
    end=$(date +%s)

    echo ">> The Docker Machine Swarm is up and running"

    tottime=$(expr $end - $begin)
    echo ">> It took $tottime seconds to start the LEGA Swarm."
    ;;
  clean)
    for ((i=1;i<=$2;i+=1)); do
      docker-machine rm lega-swarm-$i -y
    done
    ;;
esac
```

Run like: `./script.sh start 2` or `./script.sh clean 2`
To set the terminal to redirect commands to swarm master `eval $(docker-machine env attx-swarm-1)`, after which the gradle commands can be run.
To unset the terminal `eval $(docker-machine env --unset)`.

2018-07-25 05:44 UTC, blankdots commented
I was able to start the stack, however the ingest task fails, seems that it cannot connect to:
```console
╰─$ gradle ingest
> Task :upload FAILED

FAILURE: Build failed with an exception.

* Where:
Script '/home/stenegru/csc/dev/LocalEGA/deployments/swarm/utils.gradle' line: 422

* What went wrong:
Execution failed for task ':upload'.
> java.net.ConnectException: Connection refused (Connection refused)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
3 actionable tasks: 3 executed
```
After changing `localhost` to the `docker-machine ip lega-swarm-1` (I am starting with one node in this setup) on lines 422, 432, 455 the ingest works. Please don't hardcode `localhost` but instead detect the ip where each service resides.

2018-07-25 05:57 UTC, blankdots commented
When trying to run `gradle deploy` after creating 3 swarm nodes i get
```console
╰─$ gradle deploy                                                                                                                                                                                              1 ↵

> Task :cega:deployCEGAStack FAILED
service cega-mq: config not found: cega.defs.json

FAILURE: Build failed with an exception.

* Where:
Build file '/home/stenegru/csc/dev/LocalEGA/deployments/swarm/cega/build.gradle' line: 108

* What went wrong:
Execution failed for task ':cega:deployCEGAStack'.
> Process 'command 'docker'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
1 actionable task: 1 executed
```
Is the deployment not ready for multi node deployment ?

2018-07-25 06:54 UTC, dtitov commented
@blankdots, you are going a little bit beyond of this PR 😄
1. The current version is not ready for Docker Machine. I was going to add support for Docker Machine in the next PR along with functionality to deploy Swarm to OpenStack (or locally via VMs just as you did).
2. To test it locally you don't have to use Docker Machine: just do `docker swarm init` on your host machine and you're ready to go. It will create a cluster containing of one manager node.
3. Hardcoding `localhost` means that the tool is meant to run on the machine where the manager node is residing. And I'm not sure if I can detect via Docker Machine, because one's Swarm may be created not using Docker Machine. 
4. I'm not sure what happened in the last scenario with three nodes, it will need investigation. But, again, my plan is to add support for Docker Machine in the next PR.

2018-07-25 07:09 UTC, blankdots commented
@dtitov Ok, understandable. That is how I set up a swarm cluster for testing, and given that:
> Also this tool doesn't (at least yet) create a Swarm cluster for you, so one needs to have it beforehand.

I did just that, created my swarm cluster :smile: 
Anyway, with one node it seems to work. So just make the changes for the custom task, and/or custom plugin and we are good to go.

2018-07-26 10:40 UTC, dtitov commented
Now it also works in a multi-node cluster created by Docker Machine:

![](https://habrastorage.org/webt/xz/8s/zq/xz8szqg0nddqnr96tbrhpbnmljk.png)

The distribution of services across nodes are random though, as I didn't introduce any deployment constraints yet.

2018-07-26 11:59 UTC, blankdots approved these changes

2018-07-26 12:06 UTC, merged