Add Data Out's keyserver to our setup
NBISweden/LocalEGA pull request #355
Opened 2018-09-14 13:21 UTC by dtitov

It can be enabled using flag `--keyserver ega` while bootstrapping.

2018-09-17 07:21 UTC, silverdaz commented
What does the data-out keyserver do that the data-in keyserver doesn't ?

2018-09-17 07:34 UTC, blankdots commented on docker/bootstrap/lega.sh
> +      - cega-eureka:cega-eureka
if the profile is `no-oss` I assume it does not require `cega-eureka` ?

2018-09-17 07:42 UTC, blankdots commented
@silverdaz 
> What does the data-out keyserver do that the data-in keyserver doesn't ?

We have been trying to align the APIs in https://github.com/EGA-archive/ega-data-api/issues/4 however the data-in keyserver (in my understanding) cannot be used by the data-out (due to some missing endpoints/functionality), thus resulting in a setup where we would have two keyservers. With this PR we are exploring the option where we would have one keyserver, in a similar idea where we would have one database https://github.com/EGA-archive/ega-data-api/issues/10

Another option is to match the functionality of the data-out keyserver in the data-in.

2018-09-17 08:11 UTC, dtitov commented on docker/bootstrap/lega.sh
> +      - cega-eureka:cega-eureka
Good point. It really can be removed in this setup.

2018-09-17 11:52 UTC, nanjiangshu commented
Hi @dtitov , I've tested with the ega keyserver and it works 👍  But it is not very straightforward to know where the flag "--keyserver ega" to be added before one look again at the Makefile. I would like to add 
```
make "ARGS=--keyserver ega" bootstrap
```
to the document for bootstrapping if the ega keyserver is going to be used.

2018-09-17 11:54 UTC, dtitov commented
Thanks for testing, I'm glad that it works. I made a flag based on the existing flag for Inbox: `--inbox min`. But feel free to bring any changes.

2018-09-17 12:00 UTC, nanjiangshu commented
I mean it is fine with the such flags but added explicitly in the README. I will add it. So probably you can approve and merge it?

2018-09-17 12:05 UTC, blankdots requested changes
see comments. also all Integration tests should pass even the `Makefile`-based.

2018-09-17 12:05 UTC, blankdots commented on docker/bootstrap/lega.sh
> +port = 8080
flag here as well: `if [[ $KEYSERVER == 'ega' ]]; then`

2018-09-17 12:38 UTC, silverdaz commented
I think the better approach is to update the current keyserver with the missing endpoints.

2018-09-17 14:08 UTC, jrambla commented
Hi gentlemen,

I'm confused that we are having non-coherent Key servers, as this task was 'done' in a previous sprint, IMU...
Could someone clarify which is the situation?
Again, such changes should be discussed at the Sprint review/planning meeting. I consider switching components a major change and would like to discuss it in depth.

Best!

Obtén l'aplicació Outlook per a l'iOS<https://aka.ms/o0ukef>

________________________________
De: Frédéric Haziza <notifications@github.com>
Data d'enviament: dilluns, de setembre 17, 2018 2:38 p. m.
Per a: NBISweden/LocalEGA
A/c: Subscribed
Assumpte: Re: [NBISweden/LocalEGA] Add Data Out's keyserver to our setup (#355)


I think the better approach is to update the current keyserver with the missing endpoints.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://github.com/NBISweden/LocalEGA/pull/355#issuecomment-421998071>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AHsiOiT6sXrkb98FMfyTyuB-82IGVRysks5ub5fVgaJpZM4WpQyj>.

2018-09-18 07:09 UTC, blankdots commented
@jrambla
This PR is part of a sprint goal we set (and agreed, for sprint 36): "Start stitching a general docker-compose for LocalEGA (Data Ingestion and Data API)" and it constitutes work towards achieving that goal.

2018-09-19 07:06 UTC, blankdots requested changes
It would be nice to have the documentation attached to it, instead of doing it in another PR: https://github.com/NBISweden/LocalEGA/pull/356

2018-09-19 08:24 UTC, blankdots approved these changes
Reviewed and ega data api keyserver can be used.
With this PR we are providing the option to bootstrap with it.
Not a subject of this PR, but worth mentioning:
* Regarding the integration tests on travis, increasing sleep is not a good strategy. Waiting for the services to be up in the integration tests sounds like a more viable solution.*
* ega-data-api keyserver should have a health endpoint

2018-09-19 08:26 UTC, merged