Make everything validate flake8-docstrings
NBISweden/LocalEGA pull request #357
Opened 2018-09-19 09:25 UTC by blankdots

A continuation of this PR https://github.com/NBISweden/LocalEGA/pull/350

It might look like a lot has changed, however this PR add missing documentation to function, classes and makes sure every one of them adheres to the [PEP 257](https://www.python.org/dev/peps/pep-0257/)  docstring conventions.

Ignored rules (a bit biased on them, so we can discuss if we should ignore more or less): `E226,D203,D212,D213,D404,D100,D104`

Documentation of the functions is minimal and any changes or suggestion to the descriptions are welcomed.

2018-09-19 11:14 UTC, viklund requested changes
I found a few missplellings.

2018-09-19 11:14 UTC, viklund commented on lega/utils/db.py
> +    """Mark file in completed."""
Should be "Mark file completed" (possibly "_as_ completed").

2018-09-19 11:14 UTC, viklund commented on lega/utils/exceptions.py
> +        """Return readale informal description."""
_readable_ with a _b_. Applies to all of the `__str__` methods in this file.

2018-09-19 11:14 UTC, viklund commented on lega/utils/logging.py
> +    """Json Logs formattingself.
_formattingself_?

2018-09-19 11:14 UTC, viklund commented on lega/utils/storage.py
> +        """Initialise class."""
I'm more a fan of american spelling (with a _z_), but whatever.

2018-09-19 11:23 UTC, blankdots commented on lega/utils/logging.py
> +    """Json Logs formattingself.
Auto complete back stabbed me me on this.

2018-09-19 11:23 UTC, blankdots commented on lega/utils/storage.py
> +        """Initialise class."""
ok.

2018-09-19 11:30 UTC, viklund approved these changes

2018-09-19 13:41 UTC, silverdaz approved these changes

2018-09-19 13:41 UTC, silverdaz commented on lega/ingest.py
> +    """Read a message, splits the header and sends the remainder to the backend store."""
The new text is inconsistent.

2018-09-19 13:41 UTC, silverdaz commented on lega/keyserver.py
> +    """Retrive the active key from the cache and serve it via HTTPS."""
Typo: Retrieve

2018-09-19 13:41 UTC, silverdaz commented on lega/keyserver.py
> +    """Evict from the cache if TTL expired and return the keys that survived."""  # ehh...why? /Fred
Stefan, can you address the comment at the end?

2018-09-19 13:41 UTC, silverdaz commented on lega/utils/db.py
> +    """Initialize a connection to db."""
No, it doesn't

2018-09-19 13:41 UTC, silverdaz commented on lega/utils/storage.py
> +        """Initialize POSIX storage at a path."""
Initialize backend storage to a POSIX file system's path

2018-09-20 04:11 UTC, blankdots commented on lega/utils/db.py
> +    """Initialize a connection to db."""
the log below started with `Initializing a connection to...` and got me confused.

2018-09-20 04:14 UTC, blankdots commented on lega/keyserver.py
> +    """Evict from the cache if TTL expired and return the keys that survived."""  # ehh...why? /Fred
That endpoint is something we thought of when designing the keyserver and we kept it there.
the use case was to see which keys are active.

It is not subject of this PR, but most likely it will be removed as it is deprecated.

2018-09-20 04:32 UTC, merged