shell script suggestions
NBISweden/LocalEGA pull request #365
Opened 2018-09-21 15:13 UTC by kusalananda

Some shell scripting suggestions from me. Nothing really serious.

Mostly about quoting, trailing `;` on commands, formatting, testing for empty strings etc.

No functional changes as far as I know.

2018-09-24 04:36 UTC, blankdots approved these changes

2018-09-24 04:42 UTC, blankdots requested changes
Please change so that the `dev` tag is not submitted during integration tests.

2018-09-24 04:42 UTC, blankdots commented on extras/travis_push_docker_hub.sh
> +    retag_images "PR$TRAVIS_PULL_REQUEST" dev false
This is pushing image with tag `dev` and it should not:
* https://travis-ci.org/NBISweden/LocalEGA/jobs/431543758#L522
* https://travis-ci.org/NBISweden/LocalEGA/jobs/431543758#L662

I think it is related to line 12 in this file, the way `true` or `false` is evaluated.

2018-09-24 04:50 UTC, blankdots commented on extras/travis_push_docker_hub.sh
> +    if [ -n "$push" ]; then
I think this line should be one of the below:
* `if [ "$push" = true ]; then`
* `if $push ; then`

2018-09-24 05:38 UTC, kusalananda commented on extras/travis_push_docker_hub.sh
> +    if [ -n "$push" ]; then
Yes, I was confused and thought you were testing for a non-empty string, not evaluating input as commands. I've pushed a commit that does the second of you two suggestions.

2018-09-24 05:54 UTC, blankdots approved these changes

2018-09-26 08:39 UTC, viklund approved these changes
Nice

2018-09-26 08:39 UTC, merged