Database schema isolation and Security
NBISweden/LocalEGA pull request #366
Opened 2018-09-21 21:17 UTC by silverdaz

For the moment, only used as discussion/sharing plateform with Johan.

--------- No need to merge yet -------------

This PR improves the database in 3 ways:
* Isolating concerns by introducing
   * schemas (ie, as if it was several databases)
   * multiple users with read-only or read/write permissions
* Adjusting the postgres settings to secure the database access

All connection types (whether local or over the network) require a password (and we use stronger password hashing) and we enforce SSL communication.

Security can be further enhanced by restricting the connection type to a particular network, or user.
(and of course, there is IPTables and other packet filtering). But for the moment, the latter is left aside.

2018-09-21 21:20 UTC, silverdaz commented
Connected [data-out issue #12](https://github.com/EGA-archive/ega-data-api/issues/12)

2018-09-27 12:20 UTC, viklund requested changes
I have *only* looked at the schema parts of this as of now, which I think is the most important part right now. I need to set up my own test environment better before I can start testing stuff more properly.

The two schema files `audit.sql` and `main.sql` should not be in the `docker` sub-tree. I think we should have a `schema`, `db-schema` or `sql` (or something) subdirectory in the root of the project for these things.

There's some further comments inline in the two main sql files.

2018-09-27 12:20 UTC, viklund commented on docker/images/db/main.sql
> +CREATE TABLE local_ega.main (
I think this table should be split up into (at least) 3 subtables. That are then joined in the view below.

One main table that has `id`, `status` and possibly the audit logs stuff.
One table with the `submission*` stuff
One table with the `vault*` stuff
Maybe one table with the encryption info, or if that should be in main or distributed in the subtables, I'm not sure.

It's also very strange to have a `submission_file_path` after ingestion is done, since the file is removed from the `submission` system then.

`submission_file_extension` can just as well just be part of the view since it's just a substring of `submission_file_path`.

2018-09-27 12:20 UTC, viklund commented on docker/images/db/audit.sql
> +WITH (OIDS=FALSE);
OIDS are off by default from postgresql 8.1 and onwards, so this shouldn't be needed anywhere.

2018-09-28 09:10 UTC, silverdaz commented on docker/images/db/audit.sql
> +WITH (OIDS=FALSE);
Ok. Remove them.

2018-09-28 09:24 UTC, silverdaz commented on docker/images/db/main.sql
> +CREATE TABLE local_ega.main (
Well. Yes and No.
You can combine or split and store whatever you want. If you think there is a logical unit of _submission_, then there is a _view_ about submission.
I don't see any particular structure that should be favoured over another one, apart from performance.

> It's also very strange to have a `submission_file_path` after ingestion is done, since the file is removed from the `submission` system then.

I agree, I thought so too. But see it as a log.
(For example, in case we communicate about the vault file with the submitter).

> Maybe one table with the encryption info, or if that should be in main or distributed in the subtables, I'm not sure.

I wanted it inside the main table, because, after thinking of supporting multiple encryption formats, I dropåed the idea in favour for re-ingesting/converting the files.
It is there to limit the cost in case something changes in the future (Like the Global Alliance changes the Crypt4GH format), as Jordi suggested.

2018-09-28 09:32 UTC, silverdaz commented
> The two schema files `audit.sql` and `main.sql` should not be in the `docker` sub-tree. I think we should have a `schema`, `db-schema` or `sql` (or something) subdirectory in the root of the project for these things.

Yes, there were indeed in the top directory before, when we had the openstack deployment too.

Since it seems that we only support docker-based deployments, and that every site has written their own script to piece the things together, I have moved them back again in the docker tree.

After all, theses schemas are just a setup for that docker database, not an already existing database, part of a bigger infrastructure, with other network and users constraints...
Only the code should somehow reflect the database structure/schema, and that's done with views.

2018-09-28 12:52 UTC, viklund commented on docker/images/db/main.sql
> +CREATE TABLE local_ega.main (
In general, I think the database schema (without views, triggers and functions) should be as normalised as possible. For all the advantages that bring. Having extra stuff stored in the table that is not used is an invitation for inconsistent state and confusion.

Re splitting:
Well, that's the thing isn't it. Since this isn't any application view, it should be split up into the datamodel parts and then we supply projections of the data to the different applications based on their needs. The submission table (or whatever) will probably not contain all the information that the application that wants a submission view wants (then we have (with ~73% probability) designed the database wrong).

Re logs:
For logs there are logs. It shouldn't be in the data model that's mixing concerns (and making the application unnecessary complicated). A vault file is in the vault, send the filename from there.

Re encryption:
As I said I'm not sure exactly where this information should be stored. And I don't understand how the current implementation limits the cost in the future.

2018-09-28 12:55 UTC, viklund commented
Regarding sql-file location.

I think it is helpful for people using the project if a reasonable default schema can be found somewhere in the root of the project. I mean some of our application code actually _depends_ on that there are certain functions in the database. If it is in the root, you can just document what are tables just for the test-instance to get it running and what are structures that are actually needed for the application to run.

2018-09-28 16:16 UTC, silverdaz commented on docker/images/db/main.sql
> +CREATE TABLE local_ega.main (
About the splitting: No.
Let me explain.
I agree with separation of concerns and nice data model. I'm with you on that.
But the thing is:
There is one submission entry for one vault entry and one vault entry per submission entry.
Separating in 2 tables means that the view touching both needs a join.
That join is superfluous. We don't need it.

Separating into several tables in not necessary (and kills performance with extra joins) when we have one-to-one relations. Now, apply that same reasoning to the encryption table, and you see why I have put it in the main.

Furthermore, if you don't need to whole table, you introduce views, to filter the columns. That's a different story regarding performance.

Splitting too much will make the views stitch several pieces together (using joins).
There are many log entries per vault/submission entries, so that table is separated, yes. It is a relation.

Once again, the views are the real interfaces, and what the tables are underneath is an implementation detail.

As far as this PR is concerned, we need to focus on the columns of those views (in particular the data-out, since I handled the data-in already). We need someone to update the data-out, or update the data-out views. Since the logs are separated to another schema, I'm guessing the data-out must be anyway updated.

2018-09-28 16:21 UTC, silverdaz commented
What do you say about a readthedocs page with the description of the views?
Maybe a good step towards those interfaces between components?

That page would not need to talk too much about the read-only user, or the underlying tables. (Or well, in a subsection, if someone is interested in it)

2018-10-01 07:44 UTC, viklund commented
A readthedocs page about the datamodel and such would be excellent. But it's not a replacement for having the default SQL files it in the root of the project :).

2018-10-01 07:49 UTC, viklund commented on docker/images/db/main.sql
> +CREATE TABLE local_ega.main (
But now you are arguing that the _views_ should determine the datamodel, aren't the views are there to abstract the datamodel.

If that kind of join in that view ever causes a performance problem that is solved by merging two tables (in this application), I will eat a hat. The main feature of views is that you can have `joins` and `where` clauses in them, if that is not used you might as well just have a readonly user against the underlying table.

My main concern here is that we are introducing a datamodel with many ways it can be in an inconsistent state, and for a safe and secure archive that does not sound like a good idea. It would be really nice if it was possible to have multi-table constraints so that only one table could reference another (maybe it's possible with triggers and stuff). Performance without dataintegrity is meaningless.

I'm not so concerned about the columns in the views, we just add and remove them as the code evolves.

2018-10-01 07:55 UTC, dtitov commented on docker/images/db/main.sql
> +CREATE TABLE local_ega.main (
Sorry for intrusion, just my 5 cents: joins are not superfluous and don’t kill performance if the query is created properly and the tables are indexed by corresponding columns.

2018-10-03 18:27 UTC, silverdaz commented
* OIDS removed
* Functions, Types, Tables, etc.... all isolated in their schema (away from the public schema)
* Minor update on the triggers
* For Data-Out, the download schema is updated with a table for stats and errors.
* EBI views are moved to their own file. That file is loaded but not used.

2018-10-09 08:58 UTC, viklund approved these changes
I guess this is ok. As I said previously I have only reviewed the schema parts "on paper". I have not run anything or any tests.

I still think the schema should be move out of the `docker/` subtree and split up into more tables, but we can do that in a different PR.

2018-10-09 11:37 UTC, blankdots commented on lega/utils/db.py
> +               'sslmode' : CONF.get_value('db', 'sslmode'),
this should be `d.get_value('db', 'sslmode')` .. or I am missing something ?

2018-10-11 04:18 UTC, blankdots commented
@silverdaz @viklund can we fix the conflicts and integration tests, in order for us to merge this?

2018-10-12 06:22 UTC, blankdots commented on docker/bootstrap/lega.sh
> +# Database users are 'lega_in' and 'lega_out'
I saw the discussions regarding this topic in the previous comments, but still, can we keep them configurable as they were before and default them to `lega_in` and `lega_out`?
This would leave some room for flexibility in setting up the solution, also we are allowing in `config.ini` for someone to configure the user - this might create a conflict.

2018-10-12 06:34 UTC, blankdots commented on docker/images/db/entrypoint.sh
> +#!/usr/bin/env bash
i think this setup is comparable (to some degree) with the PostgreSQL image setup provided by OpenShift (https://github.com/sclorg/postgresql-container)

2018-10-12 08:02 UTC, blankdots commented on docker/images/db/entrypoint.sh
> +# Securing the access
@silverdaz looking to debug this I run into this in ingest, not 100% sure if this is by design or how to address the issue, do we have to add the IP manually here?:
```
ingest         | [lega.utils.db][DEBUG ] (L55) Database connection error: OperationalError('FATAL:  no pg_hba.conf entry for host "`always_changing_ip`", user "lega_in", database "lega", SSL on\nFATAL:  no pg_hba.conf entry for host "`always_changing_ip`", user "lega_in", database "lega", SSL off\n',)

```

2018-10-17 19:51 UTC, silverdaz commented on docker/bootstrap/lega.sh
> +# Database users are 'lega_in' and 'lega_out'
I agree.
The user in conf.ini and the one setup by the entrypoint of the database container should match.
If you want flexibility, you only need to make those 2 above match.

2018-10-17 19:51 UTC, silverdaz commented on docker/images/db/ebi.sql
> +CREATE VIEW local_ega.ebi_files AS
This is the table that the Data-Out solution from EBI can update/change/adjust, etc...

2018-10-17 19:51 UTC, silverdaz commented on docker/images/db/entrypoint.sh
> +#!/usr/bin/env bash
Ok, then... does it offer what we need and can we use it?

2018-10-17 19:51 UTC, silverdaz commented on docker/images/db/entrypoint.sh
> +# Securing the access
I'm not fiddling with the IP, so at first glance, the bug is somewhere else.
If this sometimes works, and in some case fails, we could possibly put it on hold, and handle it when we improve the robustness of the code (that is to say, next sprint). That's just a suggestion, since I can't reproduce that bug.

2018-10-18 04:29 UTC, blankdots commented on docker/images/db/entrypoint.sh
> +# Securing the access
What i noticed is that the second `pg_hba.conf` settings don't get written/loaded ... I tried different ways to get it to work, but without success (of course even cleaning all docker related volumes and images).
It seems the issue that I am getting is (maybe) the same on travis, as it get similar errors when doing the simple makefile test.
I am trying to understand how that configuration is loaded ... reading through the PostgreSQL docs takes time, even more so when there are differences between `9.6` (that we are using) and `10` that this PR proposes.

2018-10-18 04:31 UTC, blankdots commented on docker/images/db/entrypoint.sh
> +#!/usr/bin/env bash
from what I noticed the only thing that might not match 100% is the `pg_hba.conf` although we might be able to configure it somehow.

2018-10-18 05:01 UTC, blankdots commented on docker/images/db/entrypoint.sh
> +# Securing the access
from inside PostgreSQL container:
```
postgres=# SHOW hba_file;
       hba_file        
-----------------------
 /ega/data/pg_hba.conf
(1 row)

postgres=# \q
root@db:/# cat /ega/data/pg_hba.conf
local   all             all                                     trust
host    all             all             127.0.0.1/32            trust
host    all             all             ::1/128                 trust
```

2018-10-18 06:00 UTC, blankdots commented on docker/images/db/entrypoint.sh
> +# Securing the access
the bug was in the bootstrap, after going through db entrypoint logs, noticed some files some weird errors about missing files, it was failing, even though the database was up.

2018-10-18 06:19 UTC, blankdots commented
got a bit further:
```
ingest         | [lega.utils.db][DEBUG ] (L162) Updating status file_id 1 with "In progress"
ingest         | [lega.utils.db][ERROR ] (L252) Exception: <class 'psycopg2.IntegrityError'> in /usr/lib/python3.6/site-packages/lega/utils/db.py on line: 283
ingest         | [lega.utils.db][ERROR ] (L255) IntegrityError('insert or update on table "main" violates foreign key constraint "main_status_fkey"\nDETAIL:  Key (status)=(In progress) is not present in table "status".\n',) (from user: False)
ingest         | [lega.utils.db][DEBUG ] (L142) Setting error for 1: insert or update on table "main" violates foreign key constraint "main_status_fkey"
ingest         | DETAIL:  Key (status)=(In progress) is not present in table "status".
ingest         |  | Cause: None
ingest         | [lega.utils.db][DEBUG ] (L262) Catching error on file id: 1
```

2018-10-18 06:39 UTC, blankdots commented on docker/images/db/main.sql
> +VALUES (10, 'INIT'        , 'Initializing a file ingestion'),
it seems the statuses are out of sync with the ones sent form `db.py`

2018-10-18 06:59 UTC, blankdots commented on docker/images/db/main.sql
> +VALUES (10, 'INIT'        , 'Initializing a file ingestion'),
@silverdaz when should `INIT`, `DISABLED` be triggered in `db.py` ? should they be triggered at all ?

2018-10-18 08:35 UTC, silverdaz commented on docker/images/db/main.sql
> +VALUES (10, 'INIT'        , 'Initializing a file ingestion'),
Maybe it's time to update the db.py to the latest?

2018-10-18 08:37 UTC, silverdaz commented on docker/images/db/entrypoint.sh
> +# Securing the access
It's true, the bootstrap must inject those .sql files inside the bootstrap container.

2018-10-18 08:38 UTC, silverdaz commented on docker/images/db/entrypoint.sh
> +# Securing the access
I actually inject the whole directory using `-v ${PWD}:/ega` in the Makefile.

2018-10-18 09:35 UTC, blankdots commented on docker/images/db/main.sql
> +VALUES (10, 'INIT'        , 'Initializing a file ingestion'),
let's try and we will see :)

2018-10-18 15:12 UTC, silverdaz commented
Great job fixing the other bits!
I leave it up to you to remove the `Don't Merge` tag and do merge.

2018-10-19 07:42 UTC, blankdots commented
In order to merge this we need to decide on:
* this might be a breaking change as this PR proposes PostgreSQL `10` and we have it fixed in LocalEGA to `9.6` and in EGA Data API to `9.6` as well;
* entrypoint might change depending on the deployment strategy (Kuberentes/OpenShift and Docker Swarm);
* it seems that the tables that https://github.com/EGA-archive/ega-data-api/tree/master/ega-data-api-filedatabase/src/main/resources needs are there (missing from `ebi.sql` the `download_log` and `event`) also pointed here: https://github.com/EGA-archive/ega-data-api/issues/10#issuecomment-407743725
* also requires a schema name change in the ega-data-api - this is configurable here https://github.com/EGA-archive/ega-data-api/blob/master/ega-data-api-netflix/ega-data-api-config/config-files/filedatabase2.properties#L32 (and maybe other places)

2018-10-19 09:00 UTC, silverdaz commented
@blankdots: The last 2 bullet points are indeed not updated by this PR.
You can do either way: Update now and merge, or make another PR later to update the part related to ebi.sql.

About the 2 first points: This entrypoint is related to a local deployment. You might indeed have your own database, with different requirements, and that is the job of the local instance to adjust it.
This PR, in some sense, tells you what the minimum is.

Regarding version 10, I'm using it and I don't see any issue, so, please let me know, here or through another channel, what the issues are. Either we fix them in this PR, or we do it in a later one, since the integration seems to pass. After all, it's green, isn't it?

2018-10-25 07:30 UTC, blankdots approved these changes
Instead of beating around the bush with more PRs, added the `event` and `download_log` (to the best of my limited SQL knowledge) and also some permissions in `grants.sql`. If we noticed mistakes or other requirements we can adjust as needed.
This indeed requires some configuration changes in EGA-data-api, not sure if it will require changes to code.

I approve this, as a good idea moving forward to integrating with EGA-Data-API (namely https://github.com/EGA-archive/ega-data-api/issues/10).
With regard to PostgreSQL SSL communication, not 100% sure how translatable it is with our deployments.

These being said, the changes in this PR will reflect on our current deployment strategies and the database support (we will only be able to support 10+, not 9.6+ as we currently are), so it needs to be acknowledged by whole team in order to merge it.

2018-10-25 07:33 UTC, dtitov approved these changes

2018-10-25 10:57 UTC, silverdaz commented on docker/images/db/ebi.sql
> +CREATE TABLE local_ega.file2dataset (
Well.
This last change is not applicable because we are reviewing the need for the information regarding the datasets.
So I'm not approving that last commit.
Can we review the status of the Data-Out API (especially if htsget is moved out) and put it in another PR ?

2018-10-25 11:00 UTC, silverdaz commented on docker/images/db/ebi.sql
> +CREATE TABLE local_ega.event (
I understand the `download_log` table and the code could be updated to use the other table (see the download.sql).
But I could not understand the `event` table.

2018-10-25 11:02 UTC, blankdots commented on docker/images/db/ebi.sql
> +CREATE TABLE local_ega.file2dataset (
@silverdaz you added `file2dataset`, actually in EGA-data-api was named `file_dataset` but I left it as you named it :)

2018-10-25 11:04 UTC, blankdots commented on docker/images/db/ebi.sql
> +CREATE TABLE local_ega.event (
I wanted to match what was on EGA-data-API side, and it was done. As for the purpose, best to discuss with the people implementing it.

2018-10-25 11:42 UTC, silverdaz commented on docker/images/db/ebi.sql
> +CREATE TABLE local_ega.event (
.... or leave it out from this PR and create another one...

2018-10-26 08:39 UTC, merged