Mirror of PR on ega-archive
NBISweden/LocalEGA pull request #374
Opened 2018-11-22 12:21 UTC by viklund

This is only so we can get the integration tests running.

2018-11-26 09:55 UTC, blankdots requested changes
first round of review: some misses ?

2018-11-26 09:55 UTC, blankdots commented on lega/utils/errors.py
> +        publish(org_msg, 'cega', 'files.error', correlation_id)
where does this `correlation_id` come from, don't see it defined ?

2018-11-26 09:55 UTC, blankdots commented on lega/notifications.py
> +        amqp.close()
where is `amqp` defined, maybe miss ?

2018-11-26 09:55 UTC, blankdots commented on lega/outgest.py
> +        LOG.debug('Certfile: %s', ssl_certfile, extra={'correlation_id': correlation_id})
where does the `correlation_id` come from ? also in the line below

2018-11-26 12:24 UTC, jbygdell requested changes
Rebase and split.
A PR should not contain merge commits from other PRs.

2018-11-26 12:25 UTC, jbygdell requested changes
Rebase and split.
A PR should not contain merge commits from other PRs.

2018-11-26 12:25 UTC, jbygdell requested changes
Format the commit message properly.
Descriptive title, < 80 characters long terminated by a new line.
Comprehensive description of the commit that clearly specifies what is changed and why.

2018-11-26 12:26 UTC, jbygdell requested changes
Format the commit message properly.
Descriptive title, < 80 characters long terminated by a new line.
Comprehensive description of the commit that clearly specifies what is changed and why.

2018-11-26 12:26 UTC, jbygdell requested changes
Format the commit message properly.
Descriptive title, < 80 characters long terminated by a new line.
Comprehensive description of the commit that clearly specifies what is changed and why.

2018-11-26 12:26 UTC, jbygdell requested changes
47fe5dbb5
Format the commit message properly.
Descriptive title, < 80 characters long terminated by a new line.
Comprehensive description of the commit that clearly specifies what is changed and why.

2018-11-26 12:27 UTC, jbygdell requested changes
00ccc14
Rebase and split.
A PR should not contain merge commits from other PRs.

2018-11-26 12:30 UTC, jbygdell requested changes
This commit contains other changes that does not match the commit message,
these should be split out to a separate commit to minimise confusion.

2018-11-26 18:19 UTC, silverdaz commented on lega/utils/errors.py
> +        publish(org_msg, 'cega', 'files.error', correlation_id)
It was defined as an argument, and I added to the context outside the handle_error function. I thought I could remove the argument, my bad, it was a miss. I re-added it.

2018-11-26 18:37 UTC, silverdaz commented on lega/notifications.py
> +        amqp.close()
Yes, a miss.

2018-11-27 09:56 UTC, jbygdell requested changes

2018-11-27 09:56 UTC, jbygdell commented on deploy/images/README.md
> -Later on, if the `crg/ega-*` do need to be recreated, one can type `make`.
This commit contains other changes that does not match the commit message,
these should be split out to a separate commit to minimise confusion.

2019-12-16 13:29 UTC, closed without merging