Feature/renaming
NBISweden/LocalEGA pull request #378
Opened 2018-12-07 17:18 UTC by silverdaz

### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [x] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Renaming some components

### Changes made:

I renamed some components.
And I added flake8 to tox dependencies (I think it was missing)

### Related issues:

Moves #377 forward

### Additional information:

### Release note:

### Documentation change:

### Mentions:

@blankdots

2018-12-10 11:59 UTC, jbygdell requested changes
50313cc
The path renaming docker -> deploy should go into a separate commit.

2018-12-10 12:08 UTC, jbygdell requested changes

2018-12-10 12:08 UTC, jbygdell commented on deploy/bootstrap/lega.sh
> +url = http://vault:9000
Please don't use `Vault` as name for the storage back-end, to high likelihood of reference confusion to '`Hashicorp Vault`

2018-12-10 12:08 UTC, jbygdell commented on deploy/test/Makefile
> +DOCKER_PATH=$(MAIN_REPO)/deploy
This part should go into another commit, maybe 7f2fcb38b together with parts of 50313cc

2018-12-10 12:09 UTC, jbygdell requested changes

2018-12-10 12:09 UTC, jbygdell commented on deploy/tests/src/test/resources/config.properties
> +container.label.s3 = vault
This should be merged into the previous commit, 382fcad.

2018-12-10 12:09 UTC, jbygdell requested changes

2018-12-10 12:09 UTC, jbygdell commented on deploy/bootstrap/lega.sh
> +      - EGA_EBI_AWS_ENDPOINT_URL=http://vault:${DOCKER_PORT_s3}
Same here, merge into 382fcad3

2018-12-10 12:12 UTC, jbygdell requested changes

2018-12-10 12:12 UTC, jbygdell commented on requirements.txt
> +idna==2.7
This commit message needs to be properly formatted.
Maximum 79 characters as title, the description follows below.

2018-12-10 12:59 UTC, silverdaz commented on deploy/bootstrap/lega.sh
> +url = http://vault:9000
I flip the narrative.

There is no confusion with the hashicorp vault, because there is no hashicorp vault in the setup. The keyword Vault has been used since the beginning of the project to name the backend storage, so it'll stay that way.

The day you bring in the hashicorp vault into the setup, make sure to not name it vault, as it is already used.

2018-12-10 13:04 UTC, dtitov commented on deploy/bootstrap/lega.sh
> +url = http://vault:9000
This is not accurate. The `vault` component, that we had before, was a microservice, i.e. part of the application that was doing something. S3 is not a microservice (just like the PostgreSQL is not microservice as well) - it's a storage. I don't care much about Hashicorp, but storage should not be called with a name of microservice (that we had before).

2018-12-10 13:05 UTC, silverdaz commented on deploy/tests/src/test/resources/config.properties
> +container.label.s3 = vault
I'll update the history. 

My issue is in the whole setup: I have to push some commits to fix the small bugs, to see them running on Travis. It's very slow and very incremental. Once it  works, I can of course rewrite the history, squash them all, but it's usually messy.

Do you know a better way?

2018-12-10 13:05 UTC, silverdaz commented on requirements.txt
> +idna==2.7
This should not be there after the history rewrite.

2018-12-10 13:09 UTC, dtitov commented on requirements.txt
> +idna==2.7
You don't need Travis to run tests. You can simply repeat all the steps from `travis.yml` locally to see if it works. Yes, you will have to install Java 8 to run it, but this will definitely speed up the development process.

2018-12-10 13:25 UTC, silverdaz commented on deploy/bootstrap/lega.sh
> +url = http://vault:9000
Incorrect.
Both postgres and vault are microservices.

But this is not the place for such a discussion.

2018-12-10 13:26 UTC, silverdaz commented on requirements.txt
> +idna==2.7
The tests did not compile on my machine, so I checked if Travis was complaining the same way.

2018-12-10 13:38 UTC, jbygdell commented on deploy/tests/src/test/resources/config.properties
> +container.label.s3 = vault
* git commit --fixup automatically marks your commit as a fix of a previous commit
* git rebase -i --autosquash automatically organize merging of these fixup commits and associated normal commits

2018-12-10 13:45 UTC, jbygdell requested changes

2018-12-10 13:45 UTC, jbygdell commented on README.md
>  | ingesters   | Split the Crypt4GH header and move the remainder to the storage backend. No cryptographic task, nor connection to the keyserver. |
The folder renaming docker -> deploy should go into a separate commit.

2018-12-10 13:49 UTC, silverdaz commented on README.md
>  | ingesters   | Split the Crypt4GH header and move the remainder to the storage backend. No cryptographic task, nor connection to the keyserver. |
Eh.... Wasn't that what I did?
Let me check again.

2018-12-10 13:50 UTC, dtitov commented on deploy/bootstrap/lega.sh
> +url = http://vault:9000
As mentioned [here](https://microservices.io/):

> Microservices - also known as the microservice architecture - is an architectural style that structures an application as a collection of loosely coupled services, **which implement business capabilities**.

DB engine and S3 engine don't implement buisiness logic, thus they are not microservices. Regarding the discussion: before commenting here I commented in Slack, but you didn't answer.

2018-12-10 13:51 UTC, jbygdell requested changes

2018-12-10 13:51 UTC, jbygdell commented on .travis.yml
> +    # - stage: integration tests
Why did this end up this commit, it used to be a separate commit.

2018-12-10 15:17 UTC, silverdaz commented on .travis.yml
> +    # - stage: integration tests
It is anew

2018-12-11 06:45 UTC, jbygdell requested changes

2018-12-11 06:45 UTC, jbygdell commented on deploy/bootstrap/lega.sh
> +  finalize:
This section belongs in  commit 
d0b9490

2018-12-11 10:38 UTC, silverdaz commented on deploy/bootstrap/lega.sh
> +  finalize:
Damnit, how did it get there?! I thought I had it all covered.
Alright. Fixing it.

2018-12-12 06:56 UTC, jbygdell requested changes

2018-12-12 06:56 UTC, jbygdell commented on deploy/bootstrap/lega.sh
>    # Ingestion Workers
Since you are renaming both id-mapper to finalize and s3 to vault.
You should say that in the body of the commit message, if there would have been two separate commits then the same information would have fit in then commit title.

2018-12-12 06:57 UTC, jbygdell requested changes

2018-12-12 06:57 UTC, jbygdell commented on .travis.yml
> -        - pip install -r https://raw.githubusercontent.com/NBISweden/LocalEGA-cryptor/master/requirements.txt
Remove this commit

2018-12-12 06:58 UTC, jbygdell requested changes

2018-12-12 06:58 UTC, jbygdell commented on .travis.yml
> -    #     - docker-compose ps
Remove this commit

2018-12-12 08:33 UTC, dtitov commented
After force-push my comments dissappeared, so I'll comment here once again.
1. Why rename `docker` to `deploy`? Yes it’s deployment, but it’s still Docker deployment. Both terms are correct, so why would we do anything about it? Just some redundant modifications, as for me. It was never explained neither here, nor in Slack, although I asked.
2. With `id-mapper` -> `finalize` it’s up to you, of course, because it was your idea to add this component to LocalEGA. Maybe it really needs some more generic name. Maybe not. I would personally not touch it as well, but, again, I care less about this renaming.
3. The most important here: why rename `s3` to `vault`? Some time ago we had a separate component called Vault, it was functional module (i.e. microservice). And now it would confuse at least me, that we have Vault again, but now it’s not a microservice, but just a storage server. I would rather keep it as S3. Also Jocke mentioned that `Vault` can be confused with Hashicorp’s Vault for newcomers and I agree with that. And, at last, it's called S3 in Data Out, so for the sake of consistency, we need to follow some commong naming schemas.

2018-12-12 09:11 UTC, closed without merging